#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run as root, use 'sudo' or run it as root."
  exit 1
fi

command -v dnsmasq > /dev/null 2>&1 || { echo >&2 "I require dnsmasq but it's not installed. Install it. Aborting."; exit 1; }
command -v hostapd > /dev/null 2>&1 || { echo >&2 "I require hostapd but it's not installed. Install it. Aborting."; exit 1; }
command -v iw > /dev/null 2>&1 || { echo >&2 "I require iw but it's not installed. Install it. Aborting."; exit 1; }

usage() {
  echo "Usage: $0 IFACE SSID (PSK optional)"
  echo "Example: $0 wlan0 My_WiFi 123456789"
  exit 1
}

if [ "$#" -lt 2 ]; then
  usage
fi

IFACE="$1"
SSID="$2"
PSK="$3"

echo -n "Enter a MAC address (default: empty): "
read MAC
[ "$MAC" ] && { command -v macchanger > /dev/null 2>&1 || { echo >&2 "I require macchanger but it's not installed. Install it. Aborting."; exit 1; } }

iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports 80
iptables -t nat -A OUTPUT -p icmp -j REDIRECT --to-ports 80
iptables -t nat -A OUTPUT -p udp --dport 80 -j REDIRECT --to-ports 80
iptables -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to-ports 80
iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A OUTPUT -p udp --dport 5353 -j REDIRECT --to-ports 53
iptables -t nat -A OUTPUT -p tcp --dport 5353 -j REDIRECT --to-ports 53
iptables -t nat -A OUTPUT -p udp --dport 80 -j DNAT --to-destination 192.168.1.1:80
iptables -t nat -A OUTPUT -p tcp --dport 80 -j DNAT --to-destination 192.168.1.1:80
iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 192.168.1.1:53
iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination 192.168.1.1:53
iptables -t nat -A OUTPUT -p udp --dport 5353 -j DNAT --to-destination 192.168.1.1:53
iptables -t nat -A OUTPUT -p tcp --dport 5353 -j DNAT --to-destination 192.168.1.1:53
iptables -t nat -A PREROUTING -p udp --dport 80 -j REDIRECT --to-port 80
iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 80
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-port 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-port 53
iptables -t nat -A PREROUTING -p udp --dport 5353 -j REDIRECT --to-port 53
iptables -t nat -A PREROUTING -p tcp --dport 5353 -j REDIRECT --to-port 53
iptables -t nat -A PREROUTING -p udp --dport 80 -j DNAT --to-destination 192.168.1.1:80
iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 192.168.1.1:80
iptables -t nat -A PREROUTING -p udp --dport 53 -j DNAT --to-destination 192.168.1.1:53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j DNAT --to-destination 192.168.1.1:53
iptables -t nat -A PREROUTING -p udp --dport 5353 -j DNAT --to-destination 192.168.1.1:53
iptables -t nat -A PREROUTING -p tcp --dport 5353 -j DNAT --to-destination 192.168.1.1:53
iptables -t nat -A POSTROUTING -o $IFACE -j MASQUERADE

sysctl -w net.ipv4.ip_forward=1

ip link set $IFACE down
[ "$MAC" ] && macchanger -m "$MAC"
ip addr add 192.168.1.1/24 dev $IFACE
ip link set $IFACE up

iw dev $IFACE set power_save off

if [ "$PSK" ]; then
  echo "interface=$IFACE
driver=nl80211
ieee80211ac=1
ssid=$SSID
hw_mode=g
channel=6
ht_capab=[HT40+]
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
beacon_int=100
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_passphrase=$PSK
rsn_pairwise=CCMP" >hostapd.conf
else
  echo "interface=$IFACE
driver=nl80211
ieee80211ac=1
ssid=$SSID
hw_mode=g
channel=6
ht_capab=[HT40+]
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
beacon_int=100" >hostapd.conf
fi

echo "interface=$IFACE
bind-interfaces
domain-needed
bogus-priv
no-resolv
no-hosts
expand-hosts
dhcp-range=192.168.1.30,192.168.1.254,12h
dhcp-option=option:router,192.168.1.1
listen-address=127.0.0.1
address=/#/192.168.1.1
log-dhcp
log-queries" >dnsmasq.conf

hostapd hostapd.conf -B
dnsmasq -C dnsmasq.conf -d --cache-size=0 --no-negcache

pkill hostapd
pkill dnsmasq

iptables -t nat -F
iptables -t nat -X

sysctl -w net.ipv4.ip_forward=0

ip link set $IFACE down
[ "$MAC" ] && macchanger -p
ip addr del 192.168.1.1/24 dev $IFACE
ip link set $IFACE up
