#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
  echo -e "This script must be run as root, use 'sudo' or run it as root."
  exit 1
fi

command -v dnsmasq > /dev/null 2>&1 || { echo >&2 "I require dnsmasq but it's not installed. Install it. Aborting."; exit 1; }
command -v hostapd > /dev/null 2>&1 || { echo >&2 "I require hostapd but it's not installed. Install it. Aborting."; exit 1; }

usage() {
  echo "Usage: $0 SSID IFACE PSK (optional)"
  echo "Example: $0 My_WiFi wlan0 123456"
  exit 1
}

if [ "$#" -lt 2 ]; then
  usage
fi

SSID="$1"
IFACE="$2"
PSK="$3"

iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -A PREROUTING -p tcp --dport 53 -j DNAT --to-destination 192.168.1.1:53
iptables -t nat -A PREROUTING -p udp --dport 53 -j DNAT --to-destination 192.168.1.1:53
iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 192.168.1.1:80
iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to-destination 192.168.1.1:80
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 80
iptables -t nat -A POSTROUTING -o $IFACE -j MASQUERADE

sysctl -w net.ipv4.ip_forward=1

ip link set $IFACE down
ip addr add 192.168.1.1/24 dev $IFACE
ip link set $IFACE up

if [ "$PSK" ]; then
  echo "interface=$IFACE
driver=nl80211
ssid=$SSID
hw_mode=g
channel=6
wmm_enabled=1
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_passphrase=$PSK
rsn_pairwise=CCMP" >hostapd.conf
else
  echo "interface=$IFACE
driver=nl80211
ssid=$SSID
hw_mode=g
channel=6
auth_algs=1
wmm_enabled=1" >hostapd.conf
fi

echo "interface=$IFACE
bind-interfaces
domain-needed
bogus-priv
no-resolv
no-hosts
expand-hosts
server=8.8.8.8
dhcp-range=192.168.1.30,192.168.1.254,12h
dhcp-option=3,192.168.1.1
dhcp-option=6,192.168.1.1
listen-address=127.0.0.1
address=/#/192.168.1.1
log-dhcp
log-queries" >dnsmasq.conf

hostapd hostapd.conf -B
dnsmasq -C dnsmasq.conf -d --cache-size=0

pkill hostapd
pkill dnsmasq

iptables -F

sysctl -w net.ipv4.ip_forward=0

ip link set $IFACE down
ip addr del 192.168.1.1/24 dev $IFACE
ip link set $IFACE up
